spring.application.name=notification-service

server.port=9093

server.servlet.context-path=/notifications

spring.datasource.url=jdbc:postgresql://notification-db:5432/notifications

spring.datasource.username=postgres
spring.datasource.password=Gagangk@12

spring.jpa.hibernate.ddl-auto=update

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka/