version: '3.8'

services:
 kafka:
   image: docker.io/apache/kafka:4.0.1
   container_name: kafka
   volumes:
     - "kafka_data:/apache"
   networks:
     - linkedin-network
   environment:
     # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9095,CONTROLLER://kafka:9096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9095
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9096
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

 notification-db:
  image: postgres:15
  container_name: notification-db 
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: Gagangk@12
   POSTGRES_DB: notifications
  ports:
   - "5432:5432"
  networks:
     - linkedin-network
  volumes:
    - notification-db-data:/var/lib/postgresql/data

 connection-db: 
   image: neo4j
   # or use neo4j:enterprise if you have a license
   container_name: connection-db 
   ports:
   - "7474:7474" # HTTP web interface
   - "7687:7687" # Bolt protocol
   environment: 
     NEO4J_AUTH: neo4j/Gagangk@12 
     NEO4J_dbms_memory_heap_initial__size: 512m
     NEO4J_dbms_memory_heap_max__size: 1G
     NEO4J_dbms_memory_pagecache_size: 512m
   networks:
      - linkedin-network
   volumes: 
      - connection-db-data:/data 
 user-db:
  image: postgres:15
  container_name: user-db 
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: Gagangk@12
   POSTGRES_DB: userdetails
  networks:
     - linkedin-network
  volumes:
    - user-db-data:/var/lib/postgresql/data

 posts-db:
  image: postgres:15
  container_name: posts-db 
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: Gagangk@12
   POSTGRES_DB: linkpost
  networks:
     - linkedin-network
  volumes:
    - posts-db-data:/var/lib/postgresql/data

 discovery-service:
   image: gagangk/linkedin-app/discovery-service
   container_name: discovery-service
   networks:
     - linkedin-network
   ports:
     - "8761:8761"

 notification-service:
    image: gagangk/linkedin-app/notification-service
    container_name: notification-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - notification-db
      - kafka
      - api-gateway
 posts-service:
    image: gagangk/linkedin-app/posts-service
    container_name: posts-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - posts-db
      - kafka
      - user-service
      - api-gateway

 user-service:
    image: gagangk/linkedin-app/user-service
    container_name: user-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - user-db

  connection-service:
    image: gagangk/linkedin-app/connection-service
    container_name: connection-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
      - connection-db
      - kafka
      - api-gateway

 api-gateway:
    image: gagangk/linkedin-app/api-gateway
    container_name: api-gateway
    networks:
      - linkedin-network
    depends_on:
      - discovery-service
  
  

networks:
  linkedin-network:

volumes:
  kafka_data:
  notification-db-data:
  user-db-data:
  posts-db-data:
  connection-db-data:

