spring.application.name=posts-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/linkpost
spring.datasource.username=postgres
spring.datasource.password=Gagangk@12
spring.jpa.hibernate.ddl-auto=update